name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ develop, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      # For when we have build steps
      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test -- --coverage

      # For future coverage reports:
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
