name: Release

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  contents: write  # needed for tags & changelog commits

jobs:
  release:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    env:
      HUSKY: 0  # disable any local git hooks

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0       # get full history so semantic-release can find tags
          persist-credentials: true

      - name: Print CI flags
        run: |
          echo "CI=$CI"
          echo "GITHUB_ACTIONS=$GITHUB_ACTIONS"
          echo "HUSKY=$HUSKY"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}       # already set to no-publish for npm
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
